# File handling
image_directory: "data/rgb"   # Path to the RGB Files
height_data_path: "data/nDSM" # Path to the corresponding nDSM Fiels

combined_model: "data/model_combined.pth"   # or specify the urban_model and forrest_model separately
urban_model: "data/model_combined.pth"      # optional if combined_model is not used
forrest_model: "data/model_forrest.pth"     # optional if combined_model is not used
forrest_outline: "data/BW-Waldflächen/Waldflächen.shp"  # optional if combined_model is not used

output_directory: "output"  # Path to output directory, default: ./output
tiles_path: "tiles"         # Path to intermediate tile directory, default: ./tiles

image_regex: "FDOP20_(\\d+)_(\\d+)_rgbi\\.tif"  # Regex for extracting identifier out of filepath, to match image and height, default: ".*_fdop.tif"
height_data_regex: "nDSM_(\\d+)_1km\\.tif"      # Regex for extracting identifier out of filepath, to match image and height, default: ".*_nDSM.tif"

# Tile parameters
tile_width: 50    # default: 50
tile_height: 50   # default: 50
buffer: 20        # default: 20
batch_size: 10    # Predictions Batch size, typically rule of thumb 1 per GB on GPU, monitor GPU usgae in prediction in order to optimize

# Post-processing files
exclude_files:  # default: []
  - "data/BW-Gewaesser/Gewaesserflaechen.shp" # Shapefiles of different objects, that can be occluded, e.g. bodies of water or building outlines.

# Post-processing parameters
ndvi_scaling_factor: 0.2    # default: 0.2, as the NDVI is 5x larger than the Height data array. We want both to be the same scale so that we can process them together.
height_scaling_factor: 1.0  # default 1.0
confidence_threshold: 0.3   # default: 0.3 
containment_threshold: 0.6  # default: 0.9
height_threshold: 3         # default: 3
ndvi_mean_threshold: 0.15   # default: 0.05, very conservative, but should be safest for most cases
ndvi_var_threshold: 0.05    # default: 0.1

# Stiching & Cleaning parameters
iou_threshold: 0.6                    # default: 0.5
confidence_threshold_stitching: 0.3   # default: 0.3
area_threshold: 1                      # default: 1

# Device and parallelization
parallel: True  # default: true
num_workers: 5  # default: 10

# Logging and debugging
verbose: False            # default: false
debug: False              # default: false
keep_intermediate: False  # default: false