# File handling
image_directory: "data/rgb"       # Location of all GeoTIFs-Files that we want to infer
height_data_path: "data/nDSM"     # Corresponding nDSM data to the TIF files
image_regex: "FDOP20_(\\d+)_(\\d+)_rgbi\\.tif"       # Image Regex to extract a identifier from the file name, examples: "FDOP20_(\d+)_rgbi\.tif","FDOP20_(\\d+)_(\\d+)_rgbi\\.tif"
height_data_regex: "nDSM_(\\d+)_1km\\.tif" # Corresponding height regex to associate the nDSM data

image_merged_regex: "FDOP20_(\\d+)_(\\d+)_(\\d+)_(\\d+)_rgbi\\.tif"
height_data_merged_regex: "nDSM_(\\d+)(\\d+)_1km\\.tif"

#combined_model: "data/model_combined.pth"              # I) make combined prediction or specify the urban_model and forrest_model separately
urban_model: "data/model_combined.pth"                  # II) specify the urban model
forrest_model: "data/model_forrest.pth"                 # II) specify the forrest model
forrest_outline: "data/BW-Waldflächen/Waldflächen.shp"  # II) specify the forrest outline

output_directory: "output"        # Output folder, default: ./output
tiles_path: "tiles"               # Intermediate folder for tiling, default: ./tiles
merged_path: "merged"             # default: ./merged
#continue_path: "continue.yml"      # default: ./output/continue.yml

# Overlap
overlapping_tiles_width: 3
overlapping_tiles_height: 3

# Tile parameters
tile_width: 50    # default: 50
tile_height: 50   # default: 50
buffer: 20        # default: 20
batch_size: 10    # Predictions Batch size, typically rule of thumb 1 per GB on GPU, monitor GPU usgae in prediction in order to optimize this value

# Post-processing files
exclude_files:  # list of area-files that contain no trees at all, e.g. buildings, seas, rivers etc.
  - "data/BW-Gewaesser/Gewaesserflaechen.shp"

# Scaling for possible efficiency tradeoffs
ndvi_scaling_factor: 0.2   # default: 0.2, resolution dependent parameter for NDVI calculation
height_scaling_factor: 1.0 # default 1.0

# Thresholds for cleaning in postprocessing
confidence_threshold: 0.3    # default: 0.3
containment_threshold: 0.75  # default: 0.9
height_threshold: 3  # default: 3
ndvi_mean_threshold: 0.1
ndvi_var_threshold: 0.1

# Stiching & Cleaning parameters after prediction
iou_threshold: 0.6                    # default: 0.5
confidence_threshold_stitching: 0.3   # default: 0.3
area_threshold: 1                      # default: 1

# Device and parallelization
parallel: True  # default: true
num_workers: 5  # default: 10

# Logging and debugging
verbose: False            # default: false
debug: False              # default: false
keep_intermediate: False  # default: false
timestamped_output_directory: True