# File handling
#image_directory: "data/rgb_test" #"data/locations/rgb"
#height_data_path: "data/nDSM_test"  #"data/nDSM"
#image_regex: "FDOP20_(\\d+)_rgbi_epsg25832.tif" # examples "FDOP20_(\d+)_rgbi\.tif"  # default: ".*_fdop.tif"
image_directory: "data/locations/rgb"
height_data_path: "data/locations/heights"
#combined_model: "data/model_combined.pth"  # I) make combined prediction or specify the urban_model and forrest_model separately
urban_model: "data/model_combined.pth"  # II) specify the urban model
forrest_model: "data/model_forrest.pth"  # II) specify the forrest model
forrest_outline: "data/BW-Waldflächen/Waldflächen.shp"  # II) specify the forrest outline
output_directory: "output"  # default: ./output
tiles_path: "tiles"  # default: ./tiles
# continue_path: "/home/jonas/tree_detection/tree_detection/output/continue.yml"  # default: ./output/continue.yml
image_regex: "FDOP20_(\\d+)_(\\d+)_rgbi\\.tif" # examples "FDOP20_(\d+)_rgbi\.tif"  # default: ".*_fdop.tif"
height_data_regex: "nDSM_(\\d+)_1km\\.tif"  # default: ".*_nDSM.tif"

# Tile parameters
tile_width: 50    # default: 50
tile_height: 50   # default: 50
buffer: 20        # default: 20
batch_size: 10    # Predictions Batch size, typically rule of thumb 1 per GB on GPU, monitor GPU usgae in prediction in order to optimize

# Post-processing files
exclude_files:  # default: []
  - "data/BW-Gewaesser/Gewaesserflaechen.shp"

ndvi_scaling_factor: 0.2 # default: 0.2, resolution dependent parameter for NDVI calculation
height_scaling_factor: 1.0 # default 1.0

confidence_threshold: 0.3  # default: 0.3 
containment_threshold: 0.75  # default: 0.9
height_threshold: 3  # default: 3

# Stiching & Cleaning parameters
iou_threshold: 0.6                    # default: 0.5
confidence_threshold_stitching: 0.3   # default: 0.3
area_threshold: 1                      # default: 1

# Device and parallelization
parallel: True  # default: true
num_workers: 5  # default: 10

# Logging and debugging
verbose: False  # default: false
debug: True  # default: false
keep_intermediate: False  # default: false
ndvi_mean_threshold: 0.1
ndvi_var_threshold: 0.1
